// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlG902e_FLthIcT7FQNLhM58ejBCs_XwE',
    appId: '1:865398560059:web:cc9b236d77f5ae9015131e',
    messagingSenderId: '865398560059',
    projectId: 'flutterecomapp-4670c',
    authDomain: 'flutterecomapp-4670c.firebaseapp.com',
    storageBucket: 'flutterecomapp-4670c.appspot.com',
    measurementId: 'G-HZ5HTX3T3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgLoj-6YhOpwoUqq3-BI_N-RHYZR3OIzY',
    appId: '1:865398560059:android:b5ff64d67f26b53115131e',
    messagingSenderId: '865398560059',
    projectId: 'flutterecomapp-4670c',
    storageBucket: 'flutterecomapp-4670c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRwsroqNKgvPSxcyhN_I3RhglHbtUgCPs',
    appId: '1:865398560059:ios:8a75b89778949afe15131e',
    messagingSenderId: '865398560059',
    projectId: 'flutterecomapp-4670c',
    storageBucket: 'flutterecomapp-4670c.appspot.com',
    iosBundleId: 'com.example.flutterEcomFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRwsroqNKgvPSxcyhN_I3RhglHbtUgCPs',
    appId: '1:865398560059:ios:1e308cd21289e2e115131e',
    messagingSenderId: '865398560059',
    projectId: 'flutterecomapp-4670c',
    storageBucket: 'flutterecomapp-4670c.appspot.com',
    iosBundleId: 'com.example.flutterEcomFirebase.RunnerTests',
  );
}
